In [1]:
import math
import numpy as np
import random

In [2]:
def dist(x, y):
    res = 0.0
    for i in range(len(x)):
        res += (y[i] - x[i]) ** 2
    return math.sqrt(res)

In [3]:
eps = 0.001
max_iter_num = 100000

def jacobySolve(A, b):
    n = len(A)
    B = []
    d = []
    for i in range(n):
        d.append(b[i] / A[i][i])
        B.append([])
        for j in range(n):
            B[i].append(-A[i][j] / A[i][i])
        B[i][i] = 0.0
    
    detB = np.linalg.det(B)
    eps1 = eps
    if (detB >= 0.5):
        eps1 *= (1.0 - detB) / detB
        
    x_next = d.copy()
    x_cur = [0.0] * n
    iter_num = 0
    while(dist(x_next, x_cur) >= eps1 and iter_num < max_iter_num or iter_num == 0):
        x_cur = x_next.copy()
        for i in range(n):
            x_next[i] = d[i]
            for j in range(n):
                x_next[i] += B[i][j] * x_cur[j]
        iter_num += 1
    
    return (x_next, iter_num)

In [4]:
def test(A, b):
    print(f"A: {A}")
    print(f"cond: {np.linalg.cond(A)}")
    print(f"b: {b}")
    (x, iter_num) = jacobySolve(A, b)
    print(f"x: {x}")
    print(f"solution: {np.linalg.solve(A,b)}")
    print(f"iter_num: {iter_num}\n")

In [5]:
def wellConditionedMatrix(num):
    return {
        3: [[17, 2, 4], [8, 22, 10], [1, 2, 5]],
        4: [[8, 2, 4, 1], [8, 39, 10, 3], [1, 2, 7, 1], [5, 2, 1, 15]],
        5: [[15, 2, 4, 1, 3], [8, 39, 10, 3, 9], [1, 2, 10, 1, 2], [5, 2, 1, 18, 6], [4, 4, 4, 3, 40]]
    }[num]

In [6]:
def randomMatrix(size):
    return [randomCol(size) for i in range(size)]

In [7]:
def hilbertMatrix(n):
    H = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            H[i, j] = 1.0 / (i + j + 1.0)
    return H

In [8]:
min = 1
max = 10

def randomCol(n):
    return [np.random.randint(min, max) for i in range(n)]

In [9]:
test(wellConditionedMatrix(3), randomCol(3))
test(wellConditionedMatrix(4), randomCol(4))
test(wellConditionedMatrix(5), randomCol(5))

A: [[17, 2, 4], [8, 22, 10], [1, 2, 5]]
cond: 7.575611824345972
b: [6, 8, 5]
x: [0.127339695763627, -0.15335738359510348, 1.0361062792714668]
solution: [ 0.12724758 -0.15352697  1.03596127]
iter_num: 14

A: [[8, 2, 4, 1], [8, 39, 10, 3], [1, 2, 7, 1], [5, 2, 1, 15]]
cond: 8.3480302218249
b: [8, 2, 7, 3]
x: [0.5771607147248876, -0.32539884908084243, 1.0130701933793684, -0.016306234701142286]
solution: [ 0.57697196 -0.32553271  1.01293458 -0.0164486 ]
iter_num: 16

A: [[15, 2, 4, 1, 3], [8, 39, 10, 3, 9], [1, 2, 10, 1, 2], [5, 2, 1, 18, 6], [4, 4, 4, 3, 40]]
cond: 5.724417216433274
b: [5, 2, 7, 9, 3]
x: [0.15098686366017136, -0.18334958395997983, 0.681565682107905, 0.4485754836094435, -0.023452127721555013]
solution: [ 0.15087936 -0.18347072  0.68146491  0.44845606 -0.02352156]
iter_num: 14



In [10]:
test(randomMatrix(3), randomCol(3))
test(randomMatrix(4), randomCol(4))
test(randomMatrix(5), randomCol(5))

A: [[4, 3, 5], [9, 1, 3], [6, 3, 1]]
cond: 6.200203848501368
b: [5, 6, 4]


OverflowError: (34, 'Result too large')

In [11]:
test(hilbertMatrix(3), randomCol(3))
test(hilbertMatrix(4), randomCol(4))
test(hilbertMatrix(5), randomCol(5))

A: [[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
cond: 524.0567775860644
b: [7, 8, 9]
x: [-inf, nan, nan]
solution: [  45. -336.  390.]
iter_num: 1301

A: [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
cond: 15513.738738928138
b: [5, 6, 6, 6]
x: [-inf, nan, nan, nan]
solution: [  -40.   480. -1320.   980.]
iter_num: 747

A: [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]
cond: 476607.25024172297
b: [2, 2, 9, 4, 4]
x: [-inf, nan, nan, nan, nan]
solution: [   5820.         -103980.          435120.00000003 -643440.00000008
  309960.00000005]
iter_n

c:\users\xiaomi\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in double_scalars
  after removing the cwd from sys.path.
c:\users\xiaomi\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:28: RuntimeWarning: overflow encountered in double_scalars
c:\users\xiaomi\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:28: RuntimeWarning: invalid value encountered in double_scalars
