In [1]:
import math
import numpy as np
import random

In [2]:
def dist(x, y):
    res = 0.0
    for i in range(len(x)):
        res += (y[i] - x[i]) ** 2
    return math.sqrt(res)

In [3]:
eps = 0.001
max_iter_num = 100000

def jacobySolve(A, b):
    n = len(A)
    B = []
    d = []
    for i in range(n):
        d.append(b[i] / A[i][i])
        B.append([])
        for j in range(n):
            B[i].append(-A[i][j] / A[i][i])
        B[i][i] = 0.0
    
    detB = np.linalg.det(B)
    eps1 = eps
    if (detB >= 0.5):
        eps1 *= (1.0 - detB) / detB
        
    x_next = d.copy()
    x_cur = [0.0] * n
    iter_num = 0
    while(dist(x_next, x_cur) >= eps1 and iter_num < max_iter_num or iter_num == 0):
        x_cur = x_next.copy()
        for i in range(n):
            x_next[i] = d[i]
            for j in range(n):
                x_next[i] += B[i][j] * x_cur[j]
        iter_num += 1
    
    return (x_next, iter_num)

In [4]:
def test(A, b):
    print(f"A: {A}")
    print(f"cond: {np.linalg.cond(A)}")
    print(f"b: {b}")
    (x, iter_num) = jacobySolve(A, b)
    print(f"x: {x}")
    print(f"solution: {np.linalg.solve(A,b)}")
    print(f"iter_num: {iter_num}\n")

In [5]:
def wellConditionedMatrix(num):
    return {
        3: [[17, 2, 4], [8, 22, 10], [1, 2, 5]],
        4: [[8, 2, 4, 1], [8, 39, 10, 3], [1, 2, 7, 1], [5, 2, 1, 15]],
        5: [[15, 2, 4, 1, 3], [8, 39, 10, 3, 9], [1, 2, 10, 1, 2], [5, 2, 1, 18, 6], [4, 4, 4, 3, 40]]
    }[num]

In [6]:
def randomMatrix(size):
    return [randomCol(size) for i in range(size)]

In [7]:
def hilbertMatrix(n):
    H = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            H[i, j] = 1.0 / (i + j + 1.0)
    return H

In [8]:
min = 1
max = 10

def randomCol(n):
    return [np.random.randint(min, max) for i in range(n)]

In [9]:
test(wellConditionedMatrix(3), randomCol(3))
test(wellConditionedMatrix(4), randomCol(4))
test(wellConditionedMatrix(5), randomCol(5))

A: [[17, 2, 4], [8, 22, 10], [1, 2, 5]]
cond: 7.575611824345972
b: [8, 7, 2]
x: [0.39408719254160085, 0.03507912186466375, 0.30688832794802273]
solution: [0.39419087 0.03526971 0.30705394]
iter_num: 13

A: [[8, 2, 4, 1], [8, 39, 10, 3], [1, 2, 7, 1], [5, 2, 1, 15]]
cond: 8.348030221824898
b: [7, 3, 2, 6]
x: [0.7971180732602358, -0.14727517224147393, 0.19358287125075108, 0.14079101987204323]
solution: [ 0.79730841 -0.14714019  0.19371963  0.14093458]
iter_num: 15

A: [[15, 2, 4, 1, 3], [8, 39, 10, 3, 9], [1, 2, 10, 1, 2], [5, 2, 1, 18, 6], [4, 4, 4, 3, 40]]
cond: 5.724417216433276
b: [7, 9, 6, 9, 1]
x: [0.31080221790934925, 0.017734054420321582, 0.5428685838643432, 0.41273423210486127, -0.09297573575258344]
solution: [ 0.31068652  0.01760368  0.54276013  0.4126057  -0.09305046]
iter_num: 14



In [10]:
test(randomMatrix(3), randomCol(3))
test(randomMatrix(4), randomCol(4))
test(randomMatrix(5), randomCol(5))

A: [[6, 6, 4], [6, 1, 4], [5, 8, 5]]
cond: 20.062764474996456
b: [8, 6, 1]


OverflowError: (34, 'Result too large')

In [11]:
test(hilbertMatrix(3), randomCol(3))
test(hilbertMatrix(4), randomCol(4))
test(hilbertMatrix(5), randomCol(5))

A: [[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
cond: 524.0567775860644
b: [6, 5, 3]
x: [inf, nan, nan]
solution: [ -36.  204. -180.]
iter_num: 1302

A: [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
cond: 15513.73873892924
b: [9, 9, 6, 3]
x: [inf, inf, inf, nan]
solution: [   84. -1440.  4140. -2940.]
iter_num: 746

A: [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]
cond: 476607.25024259434
b: [8, 4, 8, 5, 8]
x: [-inf, nan, nan, nan, nan]
solution: [   5440.00000003 -100800.00000065  433440.00000287 -654080.00000441
  320040.00000219]
iter_num:

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in double_scalars
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:28: RuntimeWarning: overflow encountered in double_scalars
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:28: RuntimeWarning: invalid value encountered in double_scalars


In [117]:
# a1 = np.random.randint(0, 100, (3, 3))
# b1 = np.random.randint(0, 100, (3))
# np.linalg.solve(a1, b1)
# (x, iter_num) = jacobySolve(a1, b1, 0.0001)
# print(x)
a2 = [[2, 1], [1, 2]]
b2 = [1, 2]

(x, iter_num) = jacobySolve(a2, b2, 0.0001)
print(x)
np.linalg.solve(a2, b2)
# print(iter_num)

[3.0517578125e-05, 1.0]


array([0., 1.])