In [1]:
import math
import numpy as np
import random

In [2]:
def dist(x, y):
    res = 0.0
    for i in range(len(x)):
        res += (y[i] - x[i]) ** 2
    return math.sqrt(res)

In [3]:
eps = 0.001
max_iter_num = 100000

def jacobySolve(A, b):
    n = len(A)
    B = []
    d = []
    for i in range(n):
        d.append(b[i] / A[i][i])
        B.append([])
        for j in range(n):
            B[i].append(-A[i][j] / A[i][i])
        B[i][i] = 0.0
    
    normB = np.linalg.norm(B)
    print(f"normB: {normB}")
    eps1 = eps
    if (normB >= 0.5):
        eps1 *= (1.0 - normB) / normB
        
    x_next = d.copy()
    x_cur = [0.0] * n
    iter_num = 0
    while(dist(x_next, x_cur) >= eps1 and iter_num < max_iter_num or iter_num == 0):
        x_cur = x_next.copy()
        for i in range(n):
            x_next[i] = d[i]
            for j in range(n):
                x_next[i] += B[i][j] * x_cur[j]
        iter_num += 1
    
    return (x_next, iter_num)

In [4]:
def test(A, b):
    print(f"A: {A}")
    print(f"cond: {np.linalg.cond(A)}")
    print(f"b: {b}")
    (x, iter_num) = jacobySolve(A, b)
    print(f"x: {x}")
    print(f"solution: {np.linalg.solve(A,b)}")
    print(f"iter_num: {iter_num}\n")

In [5]:
def wellConditionedMatrix(num):
    return {
        3: [[17, 2, 4], [8, 22, 10], [1, 2, 5]],
        4: [[8, 2, 4, 1], [8, 39, 10, 3], [1, 2, 7, 1], [5, 2, 1, 15]],
        5: [[15, 2, 4, 1, 3], [8, 39, 10, 3, 9], [1, 2, 10, 1, 2], [5, 2, 1, 18, 6], [4, 4, 4, 3, 40]]
    }[num]

In [6]:
def randomMatrix(size):
    return [randomCol(size) for i in range(size)]

In [7]:
def hilbertMatrix(n):
    H = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            H[i, j] = 1.0 / (i + j + 1.0)
    return H

In [8]:
min = 1
max = 10

def randomCol(n):
    return [np.random.randint(min, max) for i in range(n)]

In [9]:
test(wellConditionedMatrix(3), randomCol(3))
test(wellConditionedMatrix(4), randomCol(4))
test(wellConditionedMatrix(5), randomCol(5))

A: [[17, 2, 4], [8, 22, 10], [1, 2, 5]]
cond: 7.575611824345972
b: [5, 8, 6]
normB: 0.7797737668425032
x: [0.018015589866597737, -0.2281514431674323, 1.2877454184599741]
solution: [ 0.01798064 -0.22821577  1.28769018]
iter_num: 16

A: [[8, 2, 4, 1], [8, 39, 10, 3], [1, 2, 7, 1], [5, 2, 1, 15]]
cond: 8.348030221824898
b: [8, 6, 1, 5]
normB: 0.8352534183228322
x: [1.0063275883544722, -0.056639412984394566, 0.014688128343194384, 0.004521592475817941]
solution: [ 1.00628037 -0.0566729   0.01465421  0.00448598]
iter_num: 18

A: [[15, 2, 4, 1, 3], [8, 39, 10, 3, 9], [1, 2, 10, 1, 2], [5, 2, 1, 18, 6], [4, 4, 4, 3, 40]]
cond: 5.724417216433276
b: [8, 9, 8, 6, 1]
normB: 0.7997858680932451
x: [0.33670741082458105, -0.030416837549701852, 0.7690111440098211, 0.2337740137073131, -0.1000925723609705]
solution: [ 0.33673575 -0.0303849   0.76903771  0.2338055  -0.10007427]
iter_num: 17



In [10]:
test(randomMatrix(3), randomCol(3))
test(randomMatrix(4), randomCol(4))
test(randomMatrix(5), randomCol(5))

A: [[6, 5, 5], [1, 8, 7], [4, 9, 3]]
cond: 5.272547788200426
b: [9, 4, 2]
normB: 3.5983213678973516


OverflowError: (34, 'Result too large')

In [11]:
test(hilbertMatrix(3), randomCol(3))
test(hilbertMatrix(4), randomCol(4))
test(hilbertMatrix(5), randomCol(5))

A: [[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
cond: 524.0567775860644
b: [4, 2, 2]
normB: 2.7411473672330877
x: [-inf, nan, nan]
solution: [  24. -120.  120.]
iter_num: 1303

A: [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
cond: 15513.73873892924
b: [7, 2, 2, 9]
normB: 3.8748476672566685
x: [-inf, nan, nan, nan]
solution: [  -908.  11280. -28560.  19180.]
iter_num: 747

A: [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]
cond: 476607.25024259434
b: [5, 5, 1, 9, 2]
normB: 4.9988958531426615
x: [-inf, nan, nan, nan, nan]
solution: [ -11665.0000

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in double_scalars
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:29: RuntimeWarning: overflow encountered in double_scalars
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:29: RuntimeWarning: invalid value encountered in double_scalars
