In [1]:
import math
import random
import numpy as np

In [8]:
max_iter_num = 100000

def dist(x, y):
    return math.sqrt(sum((x[i] - y[i]) ** 2 for i in range(len(x))))

def seidel(A, b, eps = 0.001):
    n = len(A)
    B = []
    d = []
    for i in range (0, n):
        d.append(b[i] / A[i][i])
        B.append([])
        for j in range (0, n):
            B[i].append(-A[i][j] / A[i][i])
        B[i][i] = 0.0
    
    
    normB = np.linalg.norm(B)
    print(f"normB: {normB}")
    eps1 = eps
    if (normB >= 0.5):
        eps1 *= (1.0 - normB) / normB
        
    x_next = d.copy()
    x_cur = x_next.copy()
    iter_num = 0
    while(dist(x_next, x_cur) >= eps1 and iter_num < max_iter_num or iter_num == 0):
        x_cur = x_next.copy()
        for i in range (n):
            x_next[i] = d[i]
            for j in range (0, n):
                # Отличие от Якоби только в том, что мы сразу можем использовать
                # уже посчитанные x_next.
                x_next[i] += B[i][j] * (x_next[j] if i < j else x_cur[j])
        iter_num += 1
    
    return (x_next, iter_num)

In [9]:
def test(A, b):
    print(f"A: {A}")
    print(f"cond: {np.linalg.cond(A)}")
    print(f"b: {b}")
    (x, iter_num) = seidel(A, b)
    print(f"x: {x}")
    print(f"solution: {np.linalg.solve(A,b)}")
    print(f"iter_num: {iter_num}\n")

In [10]:
def wellConditionedMatrix(num):
    return {
        3: [[17, 2, 4], [8, 22, 10], [1, 2, 5]],
        4: [[8, 2, 4, 1], [8, 39, 10, 3], [1, 2, 7, 1], [5, 2, 1, 15]],
        5: [[15, 2, 4, 1, 3], [8, 39, 10, 3, 9], [1, 2, 10, 1, 2], [5, 2, 1, 18, 6], [4, 4, 4, 3, 40]]
    }[num]

In [11]:
def randomMatrix(size):
    return [randomCol(size) for i in range(size)]

In [12]:
min = 1
max = 10

def randomCol(n):
    return [np.random.randint(min, max) for i in range(n)]

In [16]:
def hilbertMatrix(n):
    H = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            H[i, j] = 1.0 / (i + j + 1.0)
    return H

In [13]:
test(wellConditionedMatrix(3), randomCol(3))
test(wellConditionedMatrix(4), randomCol(4))
test(wellConditionedMatrix(5), randomCol(5))

A: [[17, 2, 4], [8, 22, 10], [1, 2, 5]]
cond: 7.575611824345972
b: [2, 4, 5]
normB: 0.7797737668425032
x: [-0.11615766009736953, -0.2945599579283717, 1.14111816485836]
solution: [-0.11618257 -0.29460581  1.14107884]
iter_num: 16

A: [[8, 2, 4, 1], [8, 39, 10, 3], [1, 2, 7, 1], [5, 2, 1, 15]]
cond: 8.348030221824898
b: [8, 4, 4, 6]
normB: 0.8352534183228322
x: [0.784184115924334, -0.19576681537999496, 0.4964944936061923, 0.13155847717744304]
solution: [ 0.7842243  -0.19573832  0.49652336  0.13158879]
iter_num: 19

A: [[15, 2, 4, 1, 3], [8, 39, 10, 3, 9], [1, 2, 10, 1, 2], [5, 2, 1, 18, 6], [4, 4, 4, 3, 40]]
cond: 5.724417216433276
b: [6, 4, 3, 4, 2]
normB: 0.7997858680932451
x: [0.3290417558898013, -0.03923370947509961, 0.26533514918966356, 0.12535058206548064, -0.014959951816072969]
solution: [ 0.32908457 -0.03918546  0.26537528  0.12539814 -0.0149323 ]
iter_num: 15



In [14]:
test(randomMatrix(3), randomCol(3))
test(randomMatrix(4), randomCol(4))
test(randomMatrix(5), randomCol(5))

A: [[3, 6, 7], [8, 1, 6], [2, 4, 4]]
cond: 36.594192245775425
b: [7, 6, 1]
normB: 10.52114273472442


OverflowError: (34, 'Result too large')

In [17]:
test(hilbertMatrix(3), randomCol(3))
test(hilbertMatrix(4), randomCol(4))
test(hilbertMatrix(5), randomCol(5))

A: [[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
cond: 524.0567775860644
b: [5, 1, 6]
normB: 2.7411473672330877
x: [inf, nan, nan]
solution: [  189. -1068.  1050.]
iter_num: 1302

A: [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
cond: 15513.73873892924
b: [2, 1, 1, 6]
normB: 3.8748476672566685
x: [-inf, -inf, nan, nan]
solution: [  -688.   8340. -20940.  14000.]
iter_num: 747

A: [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]
cond: 476607.2502422687
b: [6, 4, 7, 6, 9]
normB: 4.9988958531426615
x: [-inf, nan, nan, nan, nan]
solution: [   3570.00

c:\users\egor\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in double_scalars
  after removing the cwd from sys.path.
c:\users\egor\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:34: RuntimeWarning: overflow encountered in double_scalars
c:\users\egor\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:34: RuntimeWarning: invalid value encountered in double_scalars
