In [1]:
import math
import numpy as np

In [2]:
def dist(x, y):
    return math.sqrt(sum((x[i] - y[i]) ** 2 for i in range(len(x))))


def SOR(A, b, eps, mo):
    n = len(A)
    B = []
    d = []
    for i in range (0, n):
        d.append(b[i] / A[i][i])
        B.append([])
        for j in range (0, n):
            B[i].append(-A[i][j] / A[i][i])
        B[i][i] = 0.0
    
    normB = np.linalg.norm(B)
    eps1 = eps
    if (normB >= 0.5):
        eps1 *= (1.0 - normB) / normB
        
    print(f"norm B: {normB}")
        
    x_next = d.copy()
    x_cur = x_next.copy()
    iter_num = 0
    while(dist(x_next, x_cur) >= eps1 or iter_num == 0):
        x_cur = x_next.copy()
        for i in range (0, n):
            x_next[i] = d[i]
            for j in range (0, n):
                x_next[i] += B[i][j] * (x_next[j] if i < j else x_cur[j])
            x_next[i] = mo * x_next[i] + (1 - mo) * x_cur[i]
        iter_num += 1
    
    return (x_next, iter_num)

In [3]:
def test(A, b, mo):
    print(f"A: {A}")
    print(f"cond: {np.linalg.cond(A)}")
    print(f"b: {b}")
    (x, iter_num) = SOR(A, b, 0.0001, mo)
    print(f"x: {x}")
    print(f"solution: {np.linalg.solve(A,b)}")
    print(f"iter_num: {iter_num}\n")

In [4]:
def wellConditionedMatrix(num):
    return {
        3: [[17, 2, 4], [8, 22, 10], [1, 2, 5]],
        4: [[8, 2, 4, 1], [8, 39, 10, 3], [1, 2, 7, 1], [5, 2, 1, 15]],
        5: [[15, 2, 4, 1, 3], [8, 39, 10, 3, 9], [1, 2, 10, 1, 2], [5, 2, 1, 18, 6], [4, 4, 4, 3, 40]]
    }[num]

In [5]:
def randomMatrix(size):
    return [randomCol(size) for i in range(size)]

In [6]:
def hilbertMatrix(n):
    H = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            H[i, j] = 1.0 / (i + j + 1.0)
    return H

In [7]:
min = 1
max = 10

def randomCol(n):
    return [np.random.randint(min, max) for i in range(n)]

In [8]:
test(wellConditionedMatrix(3), randomCol(3), 0.9)
test(wellConditionedMatrix(4), randomCol(4), 0.75)
test(wellConditionedMatrix(5), randomCol(5), 0.75)

A: [[17, 2, 4], [8, 22, 10], [1, 2, 5]]
cond: 7.575611824345972
b: [7, 4, 3]
norm B: 0.7797737668425032
x: [0.28907473020439967, -0.20746453399909967, 0.6251607172366058]
solution: [ 0.28907331 -0.20746888  0.62517289]
iter_num: 13

A: [[8, 2, 4, 1], [8, 39, 10, 3], [1, 2, 7, 1], [5, 2, 1, 15]]
cond: 8.348030221824898
b: [4, 7, 9, 9]
norm B: 0.8352534183228322
x: [-0.16995200410119154, -0.1569404106847942, 1.2701405805787407, 0.5929000565196131]
solution: [-0.16994393 -0.15693458  1.27013084  0.5928972 ]
iter_num: 13

A: [[15, 2, 4, 1, 3], [8, 39, 10, 3, 9], [1, 2, 10, 1, 2], [5, 2, 1, 18, 6], [4, 4, 4, 3, 40]]
cond: 5.724417216433276
b: [4, 8, 7, 5, 5]
norm B: 0.7997858680932451
x: [0.06844005152078472, -0.004135993290072878, 0.6657198621694811, 0.21015234430114652, 0.03623743924059808]
solution: [ 0.06843462 -0.00413573  0.66572007  0.21016465  0.03623576]
iter_num: 10



In [9]:
test(randomMatrix(3), randomCol(3), 1.25)
test(randomMatrix(4), randomCol(4), 1.25)
test(randomMatrix(5), randomCol(5), 1.25)

A: [[4, 5, 8], [1, 2, 8], [3, 7, 5]]
cond: 12.611255637958537
b: [2, 6, 7]
norm B: 4.91248409666637


OverflowError: (34, 'Result too large')

In [10]:
test(hilbertMatrix(3), randomCol(3), 1.25)
test(hilbertMatrix(4), randomCol(4), 1.25)
test(hilbertMatrix(5), randomCol(5), 1.25)

A: [[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
cond: 524.0567775860644
b: [6, 3, 9]
norm B: 2.7411473672330877
x: [inf, nan, nan]
solution: [  216. -1260.  1260.]
iter_num: 808

A: [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
cond: 15513.73873892924
b: [8, 3, 1, 9]
norm B: 3.8748476672566685
x: [-inf, nan, nan, nan]
solution: [ -1252.  15060. -37500.  24920.]
iter_num: 569

A: [[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]
cond: 476607.25024259434
b: [7, 3, 4, 8, 6]
norm B: 4.9988958531426615
x: [-inf, -inf, -inf, nan, nan]
solution: [  -394

/usr/local/Cellar/ipython/7.5.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in double_scalars
  
/usr/local/Cellar/ipython/7.5.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: overflow encountered in double_scalars
/usr/local/Cellar/ipython/7.5.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in double_scalars
/usr/local/Cellar/ipython/7.5.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:32: RuntimeWarning: overflow encountered in double_scalars
